export const MOVIES_TRENDING_SET = "MOVIES_TRENDING_SET";
export const SERIES_TRENDING_SET = "SERIES_TRENDING_SET";
export const SET_LOADING = "SET_LOADING";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
